### ISSUE TITLE
Preset scalaJSOutputKind to CommonJsModule

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scalajs-bundler#13]

**Comment by sjrd** [comment]
I don't think that's a good idea given `override lazy val trigger = allRequirements`. Because then just adding `addSbtPlugin` to the build (or *one of the dependencies of another sbt plugin*) changes the behavior of Scala.js projects in the build.

I agree `ScalaJSBundlerPlugin` should set `CommonJSModule`, but *only* if it does not trigger automatically. FWIW, I think it should not automatically trigger anyway.
