### ISSUE TITLE
Allow customization of the bundle output path.

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalajs-bundler#154]
I want to generate all artifacts to a specific folder, let's say `assets/`.

**Comment by julienrf** [comment]
The current behavior is the following: everything is written in the directory where `npm update` is executed (so that the `node_modules` can be found by webpack).

This target directory can be customized by changing the value of the `crossTarget in npmUpdate` setting. But then all the artifacts produced by scalajs-bundler (e.g. the `node_modules` directory) will be present in that target directory. I guess you want to have only the bundle in some specific directory? You can either:

- write an sbt task that moves the bundle after running `webpack` ;
- set the `output.path` property of the webpack configuration object.

**Comment by connorlanigan** [comment]
Could you give more details about how to _"set the `output.path` property of the webpack configuration object"_? Do I need to create an external webpack configuration file?

**Comment by julienrf** [comment]
Yes, you have to use a custom Webpack config file as per https://scalacenter.github.io/scalajs-bundler/cookbook.html#custom-config

**Comment by connorlanigan** [comment]
Thank you for the quick response!
Note for future readers: the following code (used as a custom Webpack config file) works for me and makes the bundler output go into a subdirectory called `assets`:
```
var path = require('path');

module.exports = require('./scalajs.webpack.config');
module.exports.output.path = path.join(module.exports.output.path, "public");
```
