### ISSUE TITLE
sbt run fails

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalajs-bundler#158]
run is trying to run the output of Scala.js. It should run the bundled output.

**Comment by julienrf** [comment]
running the output of Scala.js should work as long as you run with Node.js.

If you override the JS environment maybe you should also override the `run` task according to your needs?

**Comment by MasseGuillaume** [comment]
It fails If I require anything from the bundle for example.

**Comment by julienrf** [comment]
The `run` task has been [overriden](https://github.com/scalacenter/scalajs-bundler/blob/f2cfcf33950e7b77be8627fd9aa725e0ee3aec5f/sbt-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/ScalaJSBundlerPlugin.scala#L601-L602) so that NPM modules are available to Node.js.

What is your problem exactly? Why do you need a bundle? A bundle is aimed at being executed from a web browser environment. You should probably not execute it from the sbt `run` task. Or maybe it will work if you customize the JS environment as described in the [Scala.js documentation](http://www.scala-js.org/doc/project/js-environments.html).
