### ISSUE TITLE
Publish maven source artifacts

### ISSUE THREAD

**Issue by sumnulu** [scalacenter/scalajs-bundler#227]
So IntelliJ can automatically download source code of scalajs-bundler.

**Comment by nkgm** [comment]
I was wondering the same myself, but turns out this is a problem with IntelliJ.

As @julienrf pointed out on gitter, the sources have already been published:
https://repo1.maven.org/maven2/ch/epfl/scala/sbt-scalajs-bundler_2.12_1.0/0.18.0/

Sadly IntelliJ croaks under this naming scheme and apparently so does Sonatype, returning 404 when trying to browse the artifacts [on the web](https://search.maven.org/artifact/ch.epfl.scala/sbt-scalajs-bundler/0.18.0/jar), adding further to the confusion:
https://repo1.maven.org/maven2/ch/epfl/scala/sbt-scalajs-bundler/0.18.0/

I suppose this issue can be closed.

**Comment by julienrf** [comment]
Thank you for the explanation @nkgm :)
