### ISSUE TITLE
some npm js lib is not bundled into js-opt-bundle.js

### ISSUE THREAD

**Issue by doofin** [scalacenter/scalajs-bundler#360]
It seems that some kind of js lib is not bundled ,like https://www.npmjs.com/package/marked .

sbt Setup : 
```scala
npmDependencies in Compile ++= Seq( "marked" -> "0.8.2")

```

```scala
import scala.scalajs.js.Dynamic.{global => g}
g.marked("string") 
```

browser complains about marked is not defined.However,include this script directly via script tag works(<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>).

**Comment by sjrd** [comment]
Please elaborate, at least with some kind of reproduction. Currently this report is not actionable.

**Comment by doofin** [comment]
Sorry for that,I have add more info.

**Comment by raquo** [comment]
Just because you listed this as a dependency, doesn't mean it will be added to the bundle, only that it will be added to the list of dependencies in package.json. You also need to define a `@JSImport` in your code (see scala.js docs for the exact syntax) and then also make sure to reference the JSImport-ed `object` from a `val` so that it doesn't get dead-code-eliminated (objects are lazy so if not accessed scala.js will eliminate them from the bundle).

**Comment by doofin** [comment]
Thank you! I will have a look.

**Comment by doofin** [comment]
```scala
object f2 {
  @js.native
  @JSGlobal("marked")
  def marked(string: String): Node =
    js.native

}
```
Still not working

**Comment by sjrd** [comment]
You need to somehow use `@JSImport`, not `@JSGlobal`. (Or not using scalajs-bundler at all...)

**Comment by fdietze** [comment]
@doofin 
Here is a simple facade for marked:

https://github.com/woost/wust2/blob/master/webUtil/src/main/scala/wust/facades/marked/Marked.scala

**Comment by doofin** [comment]
Thanks! @fdietze
