### ISSUE TITLE
bundling for nodejs

### ISSUE THREAD

**Issue by MHOOO** [scalacenter/scalajs-bundler#58]
Hi there,

I tried bundling for nodejs by creating a custom webpack config:
```
var webpack = require('webpack');

module.exports = require('./scalajs.webpack.config');

// make sure all deps are for nodejs
module.exports.target = "node";
```

What I noticed is that
- The custom webpack config is not being used unless I set
  enableReloadWorkflow := false
- Furthermore, I get many warnings when running the webpack task. Here is an example:
```
[info] WARNING in ./app-backend-fastopt.js
[info] Cannot find source file 'https://raw.githubusercontent.com/scala-js/scala-js/v0.6.13/tools/scalajsenv.js': Error: Cannot resolve 'file' or 'directory' ./https://raw.githubusercontent.com/scala-js/scala-js/v0.6.13/tools/s
calajsenv.js in /home/thomas/data/gitspace/scalajs-webapp/app-backend/target/scala-2.11
```

Any idea on how to fix this?

I've created a github repo, so you can reproduce the problem:
https://github.com/MHOOO/scalajs-nodejs-react-template

**Comment by julienrf** [comment]
Hi,

Indeed, your config file is ignored when the reload workflow is enabled. I should definitely warn about that in the documentation. I was expecting that this would not be a problem in general, can you give me more information on your use case? Why isn’t it better in your situation to use `fullOptJS` to generate your .js module?

The warnings are because some of the source files are not found when building the SourceMaps. This is a known issue of Scala.js (https://github.com/scala-js/scala-js/issues/2489).

**Comment by julienrf** [comment]
@MHOOO Did my reply make things clearer? I’m thinking of closing this issue and opening another one titled “Disable the reloadWorkflow mode by default”. If you don’t have any objection I will close this issue.

**Comment by MHOOO** [comment]
Yes, your answer made things clearer. I have disabled the reload workflow, so my custom configuration is read.
Thanks for the quick response!
